name: precommit test - Compile with Multiple SDK
on:
  push:
    branches: [ main ]
  pull_request:
    branches: '**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 8
      - name: Decrypt profile.properties
        run: .github/scripts/decrypt_profile.sh
        env:
          PROFILE_PASSWORD: ${{ secrets.PROFILE_PASSWORD }}
      - name: Run test
        run: sbt clean +compile