name: precommit test - udf with multiple JDK
on:
  push:
    branches: [ main ]
  pull_request:
    branches: '**'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ 11, 17 ]
      fail-fast: false
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Install Java
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
      - name: Decrypt profile.properties
        run: .github/scripts/decrypt_profile.sh
        env:
          PROFILE_PASSWORD: ${{ secrets.PROFILE_PASSWORD }}
      - name: Set env
        run: echo 'JAVA_OPTS="--add-opens=java.base/java.io=ALL-UNNAMED --add-opens=java.base/java.nio=ALL-UNNAMED --add-opens=java.base/java.lang=ALL-UNNAMED --add-opens=java.base/java.lang.reflect=ALL-UNNAMED --add-opens=java.base/java.util=ALL-UNNAMED --add-exports=java.base/sun.nio.ch=ALL-UNNAMED --add-exports=jdk.unsupported/sun.misc=ALL-UNNAMED --add-opens=java.base/sun.security.util=ALL-UNNAMED"' >> $GITHUB_ENV
      - name: Run test
        run: sbt "testOnly com.snowflake.snowpark_test.UDTFSuite com.snowflake.snowpark_test.AlwaysCleanUDFSuite com.snowflake.snowpark_test.StoredProcedureSuite" 