name: precommit test - udf with multiple JDK
on:
  push:
    branches: [ main ]
  pull_request:
    branches: '**'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ 11, 17 ]
      fail-fast: false
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Install Java
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
      - name: Decrypt profile.properties
        run: .github/scripts/decrypt_profile.sh
        env:
          PROFILE_PASSWORD: ${{ secrets.PROFILE_PASSWORD }}
      - name: Run test
        run: mvn -Dgpg.skip test -Dsuites="com.snowflake.snowpark_test.UDTFSuite,com.snowflake.snowpark_test.AlwaysCleanUDFSuite,com.snowflake.snowpark_test.StoredProcedureSuite"
